import turtle
yurak = turtle.Turtle()
turtle.speed(0)
yurak.left(90)
yurak.width(10)
son = 1
turtle.Screen().bgcolor("aqua")
while son < 115:
    yurak.color("red")
    yurak.forward(5)
    yurak.left(2)
    son +=1
yurak.forward(327)
import turtle
yurak = turtle.Turtle()
turtle.speed(0)
yurak.left(90)
yurak.width(10)
son = 1
while son < 115:
    yurak.color("red")
    yurak.forward(5)
    yurak.right(2)
    son +=1
yurak.forward(327)
import turtle
nayza = turtle.Turtle()
turtle.speed(0)
nayza.color("aqua")
nayza.width(10)
nayza.goto(350,150)
nayza.right(155)
nayza.color("black")
nayza.forward(40)
nayza.left(145)
nayza.forward(15)
nayza.left(35)
nayza.forward(30)
nayza.left(145)
nayza.forward(15)
nayza.right(110)
nayza.forward(15)
nayza.left(145)
nayza.forward(30)
nayza.left(35)
nayza.forward(15)
nayza.right(35)
nayza.forward(210)
nayza.color("aqua")
nayza.forward(382)
nayza.color("red")
nayza.forward(13)
nayza.color("black")
nayza.forward(200)
nayza.left(145)
nayza.forward(30)
nayza.left(125)
nayza.forward(35)
nayza.left(125)
nayza.forward(30)
turtle.done()
